apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: my-cluster
  name: my-topic
spec:
  config:
    message.format.version: 2.4-IV1
    retention.ms: '604800000'
    segment.bytes: '1073741824'
  partitions: 10
  replicas: 1
  topicName: my-topic
