apiVersion: eventing.knative.dev/v1alpha1
kind: KnativeEventingKafka
metadata:
  name: knative-eventing-kafka
spec:
  bootstrapServers: 'my-cluster-kafka-bootstrap:9092'
  setAsDefaultChannelProvisioner: false
